### ISSUE TITLE
Question about python version

### ISSUE THREAD

**Issue by eblabs** [dridk/QJsonmodel#14]
https://github.com/dridk/QJsonModel/blob/1386e400fd06b95071c6ff3e95bbe732518288dc/qjsonmodel.py#L97-L124

Hi,
Great work, your new model is so helpful! Quick question, in the "load" method there are some recursive calls like this:

`child = self.load(value, rootItem)`

although the function signature is like this:
`def load(self, value, parent=None, sort=True):`

Just wanted to confim, is this root item meant to be a "parent" in the function call?

Thanks again!!

**Comment by dridk** [comment]
Thanks! 
Yes bad name. It should be rename to "item" instead of "rootItem" to avoid confusing

**Comment by eblabs** [comment]
Thanks for the quick reply @dridk ! Got it working now.
