### ISSUE TITLE
QJsonData is not displayed correctly if root object of JSON data is array

### ISSUE THREAD

**Issue by eduard-sukharev** [dridk/QJsonmodel#2]
When QJsonData is preloaded with following data:

``` JSON
[
        {
        "name" : "FOO"
    },
        {
        "name" : "BAR"
    }
]
```

then TreeView is unable to show any structure (note that parent structure is JSON array), while loading a following works just fine:

``` JSON
{
    "object1": {
        "name": "FOO"
    },
    "object2": {
        "name": "BAR"
    }
}
```

works just fine (parent structure is JSON "object", or "dictionary").

**Comment by dridk** [comment]
Because the tree model need a root item. You cannot have a [ ] as root.
Only an element.
Le 16 oct. 2015 16:25, "Eduard Sukharev" notifications@github.com a
écrit :

**Comment by dridk** [comment]
{ list: [
        {
        "name" : "FOO"
    },
        {
        "name" : "BAR"
    }
]}

Will works.

**Comment by eduard-sukharev** [comment]
@dridk then as you've said QJsonModel should auto add a root to loaded data if parent structure is an array.

and why cannot array be the root entity?

**Comment by dridk** [comment]
Because of the json hijacking ..
http://haacked.com/archive/2009/06/25/json-hijacking.aspx/

Your app encoured risk of doing this
Le 16 oct. 2015 16:32, "Eduard Sukharev" notifications@github.com a
écrit :

**Comment by eduard-sukharev** [comment]
@dridk ok, that seems legit. But you've created a json model, a generic enough class to handle JSON data to be used in views. And JSON standard allows for both arrays and objects to be on the top level of hierarchy. Which is also supported by the QJson implementation you used in qjsonmodel.
So i guess it's a bug of qjsonmodel and it can be fixed quite easily :)

**Comment by dridk** [comment]
Ok i will.  Or you can fork and correct it
Le 16 oct. 2015 18:35, "Eduard Sukharev" notifications@github.com a
écrit :
