### ISSUE TITLE
Bad keys order

### ISSUE THREAD

**Issue by yvanblanchard** [dridk/QJsonmodel#20]
Hello,
I have a JSON file , that when processed with your code, it leads to a bad order of keys (see image and JSON file attached).
Could you fix this issue ?
Thank you
![2021-09-22_09h30_51](https://user-images.githubusercontent.com/63931618/134301383-c450297c-f894-4fbd-a322-5edbd011e8f7.png)
[out_printpoints.json.txt](https://github.com/dridk/QJsonModel/files/7208661/out_printpoints.json.txt)
ou

**Comment by dridk** [comment]
By default key are sorted by alpha. You can solve this by using QSortFilterProxyModel.
https://doc.qt.io/qt-5/qsortfilterproxymodel.html

Or you can subclass QJsonModel and reimplement sort : 
https://doc.qt.io/qt-5/qabstractitemmodel.html#sort

**Comment by dridk** [comment]
By the way, keys in your json file are string not integer.

**Comment by siyuhong** [comment]
If you want to make it sequential to display,  you can use jsonarray.
jsonobject is unordered. 
@yvanblanchard
