### ISSUE TITLE
Make model editable please

### ISSUE THREAD

**Issue by Climax777** [dridk/QJsonmodel#4]
Hi and thanks for the library

It would be great if this model were editable.

**Comment by dridk** [comment]
I agree ! 
Should be easy . Need to find time and motivation !

**Comment by marcelino-m** [comment]
Done!

**Comment by tamenol** [comment]
Where did this get merged/implemented?

When I try to edit a cell I get the error `NameError: name '__binding__' is not defined` on next lines:
```python
if __binding__ in ("PySide", "PyQt5"):
    self.dataChanged.emit(index, index)
else:
    self.dataChanged.emit(index, index, [Qt.EditRole])
```

I edited it to

```python
try:
    if __binding__ in ("PySide", "PyQt5"):
        self.dataChanged.emit(index, index)
    else:
        self.dataChanged.emit(index, index, [Qt.EditRole])
except NameError:
    self.dataChanged.emit(index, index, [Qt.EditRole])
```

And I no longer got the error.
